/*
  Copyright 2022 Christos Katsakioris

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/ckatsak/acticrds-go/pkg/apis/acti.cslab.ece.ntua.gr/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeActiNodes implements ActiNodeInterface
type FakeActiNodes struct {
	Fake *FakeActiV1alpha1
	ns   string
}

var actinodesResource = schema.GroupVersionResource{Group: "acti.cslab.ece.ntua.gr", Version: "v1alpha1", Resource: "actinodes"}

var actinodesKind = schema.GroupVersionKind{Group: "acti.cslab.ece.ntua.gr", Version: "v1alpha1", Kind: "ActiNode"}

// Get takes name of the actiNode, and returns the corresponding actiNode object, and an error if there is any.
func (c *FakeActiNodes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ActiNode, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(actinodesResource, c.ns, name), &v1alpha1.ActiNode{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ActiNode), err
}

// List takes label and field selectors, and returns the list of ActiNodes that match those selectors.
func (c *FakeActiNodes) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ActiNodeList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(actinodesResource, actinodesKind, c.ns, opts), &v1alpha1.ActiNodeList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ActiNodeList{ListMeta: obj.(*v1alpha1.ActiNodeList).ListMeta}
	for _, item := range obj.(*v1alpha1.ActiNodeList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested actiNodes.
func (c *FakeActiNodes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(actinodesResource, c.ns, opts))

}

// Create takes the representation of a actiNode and creates it.  Returns the server's representation of the actiNode, and an error, if there is any.
func (c *FakeActiNodes) Create(ctx context.Context, actiNode *v1alpha1.ActiNode, opts v1.CreateOptions) (result *v1alpha1.ActiNode, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(actinodesResource, c.ns, actiNode), &v1alpha1.ActiNode{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ActiNode), err
}

// Update takes the representation of a actiNode and updates it. Returns the server's representation of the actiNode, and an error, if there is any.
func (c *FakeActiNodes) Update(ctx context.Context, actiNode *v1alpha1.ActiNode, opts v1.UpdateOptions) (result *v1alpha1.ActiNode, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(actinodesResource, c.ns, actiNode), &v1alpha1.ActiNode{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ActiNode), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeActiNodes) UpdateStatus(ctx context.Context, actiNode *v1alpha1.ActiNode, opts v1.UpdateOptions) (*v1alpha1.ActiNode, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(actinodesResource, "status", c.ns, actiNode), &v1alpha1.ActiNode{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ActiNode), err
}

// Delete takes name of the actiNode and deletes it. Returns an error if one occurs.
func (c *FakeActiNodes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(actinodesResource, c.ns, name), &v1alpha1.ActiNode{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeActiNodes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(actinodesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ActiNodeList{})
	return err
}

// Patch applies the patch and returns the patched actiNode.
func (c *FakeActiNodes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ActiNode, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(actinodesResource, c.ns, name, pt, data, subresources...), &v1alpha1.ActiNode{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ActiNode), err
}
