/*
  Copyright 2022 Christos Katsakioris

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/ckatsak/acticrds-go/pkg/apis/acti.cslab.ece.ntua.gr/v1alpha1"
	scheme "github.com/ckatsak/acticrds-go/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ActiNodesGetter has a method to return a ActiNodeInterface.
// A group's client should implement this interface.
type ActiNodesGetter interface {
	ActiNodes(namespace string) ActiNodeInterface
}

// ActiNodeInterface has methods to work with ActiNode resources.
type ActiNodeInterface interface {
	Create(ctx context.Context, actiNode *v1alpha1.ActiNode, opts v1.CreateOptions) (*v1alpha1.ActiNode, error)
	Update(ctx context.Context, actiNode *v1alpha1.ActiNode, opts v1.UpdateOptions) (*v1alpha1.ActiNode, error)
	UpdateStatus(ctx context.Context, actiNode *v1alpha1.ActiNode, opts v1.UpdateOptions) (*v1alpha1.ActiNode, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ActiNode, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ActiNodeList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ActiNode, err error)
	ActiNodeExpansion
}

// actiNodes implements ActiNodeInterface
type actiNodes struct {
	client rest.Interface
	ns     string
}

// newActiNodes returns a ActiNodes
func newActiNodes(c *ActiV1alpha1Client, namespace string) *actiNodes {
	return &actiNodes{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the actiNode, and returns the corresponding actiNode object, and an error if there is any.
func (c *actiNodes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ActiNode, err error) {
	result = &v1alpha1.ActiNode{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("actinodes").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ActiNodes that match those selectors.
func (c *actiNodes) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ActiNodeList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ActiNodeList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("actinodes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested actiNodes.
func (c *actiNodes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("actinodes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a actiNode and creates it.  Returns the server's representation of the actiNode, and an error, if there is any.
func (c *actiNodes) Create(ctx context.Context, actiNode *v1alpha1.ActiNode, opts v1.CreateOptions) (result *v1alpha1.ActiNode, err error) {
	result = &v1alpha1.ActiNode{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("actinodes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(actiNode).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a actiNode and updates it. Returns the server's representation of the actiNode, and an error, if there is any.
func (c *actiNodes) Update(ctx context.Context, actiNode *v1alpha1.ActiNode, opts v1.UpdateOptions) (result *v1alpha1.ActiNode, err error) {
	result = &v1alpha1.ActiNode{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("actinodes").
		Name(actiNode.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(actiNode).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *actiNodes) UpdateStatus(ctx context.Context, actiNode *v1alpha1.ActiNode, opts v1.UpdateOptions) (result *v1alpha1.ActiNode, err error) {
	result = &v1alpha1.ActiNode{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("actinodes").
		Name(actiNode.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(actiNode).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the actiNode and deletes it. Returns an error if one occurs.
func (c *actiNodes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("actinodes").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *actiNodes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("actinodes").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched actiNode.
func (c *actiNodes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ActiNode, err error) {
	result = &v1alpha1.ActiNode{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("actinodes").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
